version: '3'

services:
  fiber_blog:
    image: "jhonoryza/fiber_blog"
    container_name: "fiber_blog"
    restart: unless-stopped
    ports:
      - 10201:8080
    volumes:
      - ./.env:/app/.env